# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
